export const styleCode = {
    BUTTON_BACKGROUND: 'BUTTON_BACKGROUND',
    WIDGET_BACKGROUND: 'WIDGET_BACKGROUND',
    WIDGET_SQUARE_LOGO_URL: 'WIDGET_SQUARE_LOGO_URL',
    DEFAULT_CHARITY_LOGO: 'DEFAULT_CHARITY_LOGO',
    CHARITY_LINK: 'CHARITY_LINK'
};

export const color = {
    BLACK: '#000000',
    WHITE: '#FFFFFF'
};

export const imgSrcOrder = {
    SVG: 0,
    PNG: 1
};